### ISSUE TITLE
With fast browsing of soundfonts getting to busyloop

### ISSUE THREAD

**Issue by tavasti** [noedigcode/konfyt#1] opened 2018-09-30 15:06 UTC
When browsing soundfonts, and one hand playing midi keys, another clicking with mouse selecting soundfonts, pretty soon UI will freeze, no audio output and konfyt will eat one cpu core 100%

Running Ubuntu 18.04. 
libfluidsynth is 1.1.9-1  (ubuntu or kxstudio package)
carla is git version, last commit 981d11f7398155ab33e939823792433447eb673c

When browsing it does not matter are you selecting soundfonts or patches in same soundfont. And happens also when browsing with cursor keys.

**Comment by noedigcode** [comment] 2018-10-19 05:39
I have been unable to reproduce your bug. I had to install the newest Mint that is based on Ubuntu 18.04 to have the same Fluidsynth version as you. However, I cannot reproduce what you describe. I have tried several of the Newground soundfonts, as well as others.
Is there any chance you could narrow it down more? A screencast could be useful in case we're misunderstanding each other.
I'll give it some thought in the mean time.

**Comment by tavasti** [comment] 2018-10-20 14:12
- I downloaded soundfonts here: https://www.flstudiomusic.com/2010/02/49-guitar-soundfonts.html (so that we are testing with same soundfonts, althou it does not matter which soundfonts are used)
- unpacked them
- Connected audio and midi, clicked preview on
- Selected first soundfont, and started scrolling list down cursor key down, and up again while pressing keys on midi keyboard
Result was freeze again, shown in video https://youtu.be/nqJWbZa_Rng

Personally I would say it is related to QT, not soundfont handling.

**Comment by noedigcode** [comment] 2018-10-20 17:06
Thanks for the info! I managed to reproduce the bug and will hunt it down.
The bug only shows itself when compiled in release mode. Since I usually compile and run in debug mode, I was not seeing it.
In the meantime, you could compile with debug on if you want a more stable workflow for now until I track down the bug. (use qmake CONFIG+=debug)

**Comment by noedigcode** [comment] 2018-10-20 20:15
I seem to have found the bug. It should now be fixed on the master branch.
Please confirm on your side (compile in release mode, i.e. without the debug qmake option).

**Comment by tavasti** [comment] 2018-10-24 16:02
Verified, does not crash. Thanks!

**Comment by noedigcode** [comment] 2018-10-24 18:26
Cool! Thanks for reporting the bug and taking time to provide more info.

**Closed as completed by noedigcode** 2018-10-24 18:26 UTC
